sudo: false
language: go
git:
    depth: 1
before_script:
    - go get github.com/magefile/mage
    - go get -d github.com/gohugoio/hugo
    - cd ${GOPATH:-$HOME/go}/src/github.com/gohugoio/hugo
    - mage vendor
    - mage install
script:
    ‐ hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: public
    repo: jferic/jferic.github.io
    fqdn: jferic.com
    target_branch: master
    email: jferic@aliyun.com
    name: jferic
