sudo: false
language: go
go:
    - "1.10.3"
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script:
    - hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: feature/jferic
    local_dir: public
    repo: jferic/jferic.github.io
    target_branch: feature/jferic
    email: jferic@aliyun.com
    name: jferic
